version: '3'

services:
  app:
    build: .
    links:
      - redis:redis
    environment:
      REDIS_URL: redis://redis
      RAILS_ENV: test
    ports:
      - "5000:5000"
    entrypoint: wait-for-it.sh redis:6379 -s --

  redis:
    image: redis
